# Generated by Django 4.2.11 on 2026-02-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_auditlog_user_role_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_busines_704f12_idx',
            old_name='accounts_au_busines_50b2d2_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_target__0c7dca_idx',
            old_name='accounts_au_target__2daa4e_idx',
        ),
    ]
