# Generated by Django 4.2.11 on 2026-02-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_busines_585b98_idx',
            old_name='products_pro_busines_8e96b8_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_status_041708_idx',
            old_name='products_pro_status_a3ece4_idx',
        ),
    ]
